export enum ConfigEnum {
    DB_TYPE = 'DB_TYPE',
    DB_HOST = 'DB_HOST',
    DB_PORT = 'DB_PORT',
    DB_DATABASE = 'DB_DATABASE',
    DB_USERNAME = 'DB_USERNAME',
    DB_PASSWORD = 'DB_PASSWORD',
    DB_SYNC = 'DB_SYNC',
    SECRET = 'SECRET',
    REDIS_HOST = 'REDIS_HOST',
    REDIS_PORT = 'REDIS_PORT',
    REDIS_PASSWORD = 'REDIS_PASSWORD',
    REDIS_RECONNECT = 'REDIS_RECONNECT',
    APP_PORT = "APP_PORT",
    LOG_ON = "LOG_ON"
}